image:
  repository: registry.digitalocean.com/astro-blog-web/astro-blog
  tag: 767f9d8
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: registry-astro-blog-web

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: tamiilore.dev
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: astro
              port:
                number: 80
  tls:
    - hosts:
        - tamiilore.dev
      secretName: astro-tls-alt



