apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: astro-tls-legacy
  namespace: astro
  labels:
    argocd.argoproj.io/instance: astro
spec:
  secretName: astro-tls-legacy
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - tamiilore.dev
  usages:
    - digital signature
    - key encipherment
