{{- if and .Values.ingress.tls (gt (len .Values.ingress.tls) 0) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ index .Values.ingress.tls 0 "secretName" }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: {{ index (index .Values.ingress.tls 0).hosts 0 }}
  dnsNames:
    {{- range (index .Values.ingress.tls 0).hosts }}
    - {{ . }}
    {{- end }}
{{- end }}

